export const rows = [
  {
    id: 1,
    firstName: "Jon",
    lastName: "doe",
    email: "jonsnow@gmail.com",
    phone: "(665)121-5454",
    access: "Admin",
  },
  {
    id: 2,
    firstName: "Cersei",
    lastName: "Lannister",
    email: "cerseilannister@gmail.com",
    phone: "(421)314-2288",
    access: "Manager",
  },
  {
    id: 3,
    firstName: "Cersei",
    lastName: "Lannister",
    email: "cerseilannister@gmail.com",
    phone: "(421)314-2288",
    access: "Admin",
  },
  {
    id: 4,
    firstName: "Cersei",
    lastName: "Lannister",
    email: "cerseilannister@gmail.com",
    phone: "(421)314-2288",
    access: "Admin",
  },
  {
    id: 5,
    firstName: "Cersei",
    lastName: "Lannister",
    email: "cerseilannister@gmail.com",
    phone: "(421)314-2288",
    access: "Admin",
  },
  {
    id: 6,
    firstName: "Cersei",
    lastName: "Lannister",
    email: "cerseilannister@gmail.com",
    phone: "(421)314-2288",
    access: "Admin",
  },
  {
    id: 7,
    firstName: "Cersei",
    lastName: "Lannister",
    email: "cerseilannister@gmail.com",
    phone: "(421)314-2288",
    access: "Admin",
  },
  {
    id: 8,
    firstName: "Cersei",
    lastName: "Lannister",
    email: "cerseilannister@gmail.com",
    phone: "(421)314-2288",
    access: "Admin",
  },
  {
    id: 9,
    firstName: "Cersei",
    lastName: "Lannister",
    email: "cerseilannister@gmail.com",
    phone: "(421)314-2288",
    access: "Admin",
  },
  {
    id: 10,
    firstName: "Cersei",
    lastName: "Lannister",
    email: "cerseilannister@gmail.com",
    phone: "(421)314-2288",
    access: "Admin",
  },
];
